// yutool: include guard
#ifndef YU_META_FUNCTIONS_TYPE_TRAITS_HPP_
#define YU_META_FUNCTIONS_TYPE_TRAITS_HPP_

// yutool: export headers
#include "type_traits/add_const.hpp"                           // IWYU pragma: export
#include "type_traits/add_cv.hpp"                              // IWYU pragma: export
#include "type_traits/add_lvalue_reference.hpp"                // IWYU pragma: export
#include "type_traits/add_pointer.hpp"                         // IWYU pragma: export
#include "type_traits/add_rvalue_reference.hpp"                // IWYU pragma: export
#include "type_traits/add_volatile.hpp"                        // IWYU pragma: export
#include "type_traits/alignment_of.hpp"                        // IWYU pragma: export
#include "type_traits/common_reference.hpp"                    // IWYU pragma: export
#include "type_traits/common_type.hpp"                         // IWYU pragma: export
#include "type_traits/decay.hpp"                               // IWYU pragma: export
#include "type_traits/extent.hpp"                              // IWYU pragma: export
#include "type_traits/has_unique_object_representations.hpp"   // IWYU pragma: export
#include "type_traits/has_virtual_destructor.hpp"              // IWYU pragma: export
#include "type_traits/invoke_result.hpp"                       // IWYU pragma: export
#include "type_traits/is_abstract.hpp"                         // IWYU pragma: export
#include "type_traits/is_aggregate.hpp"                        // IWYU pragma: export
#include "type_traits/is_arithmetic.hpp"                       // IWYU pragma: export
#include "type_traits/is_array.hpp"                            // IWYU pragma: export
#include "type_traits/is_assignable.hpp"                       // IWYU pragma: export
#include "type_traits/is_base_of.hpp"                          // IWYU pragma: export
#include "type_traits/is_bounded_array.hpp"                    // IWYU pragma: export
#include "type_traits/is_class.hpp"                            // IWYU pragma: export
#include "type_traits/is_compound.hpp"                         // IWYU pragma: export
#include "type_traits/is_const.hpp"                            // IWYU pragma: export
#include "type_traits/is_constructible.hpp"                    // IWYU pragma: export
#include "type_traits/is_convertible.hpp"                      // IWYU pragma: export
#include "type_traits/is_copy_assignable.hpp"                  // IWYU pragma: export
#include "type_traits/is_copy_constructible.hpp"               // IWYU pragma: export
#include "type_traits/is_default_constructible.hpp"            // IWYU pragma: export
#include "type_traits/is_destructible.hpp"                     // IWYU pragma: export
#include "type_traits/is_empty.hpp"                            // IWYU pragma: export
#include "type_traits/is_enum.hpp"                             // IWYU pragma: export
#include "type_traits/is_final.hpp"                            // IWYU pragma: export
#include "type_traits/is_floating_point.hpp"                   // IWYU pragma: export
#include "type_traits/is_function.hpp"                         // IWYU pragma: export
#include "type_traits/is_fundamental.hpp"                      // IWYU pragma: export
#include "type_traits/is_integral.hpp"                         // IWYU pragma: export
#include "type_traits/is_invocable.hpp"                        // IWYU pragma: export
#include "type_traits/is_invocable_r.hpp"                      // IWYU pragma: export
#include "type_traits/is_layout_compatible.hpp"                // IWYU pragma: export
#include "type_traits/is_lvalue_reference.hpp"                 // IWYU pragma: export
#include "type_traits/is_member_function_pointer.hpp"          // IWYU pragma: export
#include "type_traits/is_member_object_pointer.hpp"            // IWYU pragma: export
#include "type_traits/is_member_pointer.hpp"                   // IWYU pragma: export
#include "type_traits/is_move_assignable.hpp"                  // IWYU pragma: export
#include "type_traits/is_move_constructible.hpp"               // IWYU pragma: export
#include "type_traits/is_nothrow_assignable.hpp"               // IWYU pragma: export
#include "type_traits/is_nothrow_constructible.hpp"            // IWYU pragma: export
#include "type_traits/is_nothrow_convertible.hpp"              // IWYU pragma: export
#include "type_traits/is_nothrow_copy_assignable.hpp"          // IWYU pragma: export
#include "type_traits/is_nothrow_copy_constructible.hpp"       // IWYU pragma: export
#include "type_traits/is_nothrow_default_constructible.hpp"    // IWYU pragma: export
#include "type_traits/is_nothrow_destructible.hpp"             // IWYU pragma: export
#include "type_traits/is_nothrow_invocable.hpp"                // IWYU pragma: export
#include "type_traits/is_nothrow_invocable_r.hpp"              // IWYU pragma: export
#include "type_traits/is_nothrow_move_assignable.hpp"          // IWYU pragma: export
#include "type_traits/is_nothrow_move_constructible.hpp"       // IWYU pragma: export
#include "type_traits/is_nothrow_swappable.hpp"                // IWYU pragma: export
#include "type_traits/is_nothrow_swappable_with.hpp"           // IWYU pragma: export
#include "type_traits/is_null_pointer.hpp"                     // IWYU pragma: export
#include "type_traits/is_object.hpp"                           // IWYU pragma: export
#include "type_traits/is_pointer.hpp"                          // IWYU pragma: export
#include "type_traits/is_pointer_interconvertible_base_of.hpp" // IWYU pragma: export
#include "type_traits/is_polymorphic.hpp"                      // IWYU pragma: export
#include "type_traits/is_reference.hpp"                        // IWYU pragma: export
#include "type_traits/is_rvalue_reference.hpp"                 // IWYU pragma: export
#include "type_traits/is_same.hpp"                             // IWYU pragma: export
#include "type_traits/is_scalar.hpp"                           // IWYU pragma: export
#include "type_traits/is_scoped_enum.hpp"                      // IWYU pragma: export
#include "type_traits/is_signed.hpp"                           // IWYU pragma: export
#include "type_traits/is_standard_layout.hpp"                  // IWYU pragma: export
#include "type_traits/is_swappable.hpp"                        // IWYU pragma: export
#include "type_traits/is_swappable_with.hpp"                   // IWYU pragma: export
#include "type_traits/is_trivially_assignable.hpp"             // IWYU pragma: export
#include "type_traits/is_trivially_constructible.hpp"          // IWYU pragma: export
#include "type_traits/is_trivially_copy_assignable.hpp"        // IWYU pragma: export
#include "type_traits/is_trivially_copy_constructible.hpp"     // IWYU pragma: export
#include "type_traits/is_trivially_copyable.hpp"               // IWYU pragma: export
#include "type_traits/is_trivially_default_constructible.hpp"  // IWYU pragma: export
#include "type_traits/is_trivially_destructible.hpp"           // IWYU pragma: export
#include "type_traits/is_trivially_move_assignable.hpp"        // IWYU pragma: export
#include "type_traits/is_trivially_move_constructible.hpp"     // IWYU pragma: export
#include "type_traits/is_unbounded_array.hpp"                  // IWYU pragma: export
#include "type_traits/is_union.hpp"                            // IWYU pragma: export
#include "type_traits/is_unsigned.hpp"                         // IWYU pragma: export
#include "type_traits/is_void.hpp"                             // IWYU pragma: export
#include "type_traits/is_volatile.hpp"                         // IWYU pragma: export
#include "type_traits/make_signed.hpp"                         // IWYU pragma: export
#include "type_traits/make_unsigned.hpp"                       // IWYU pragma: export
#include "type_traits/rank.hpp"                                // IWYU pragma: export
#include "type_traits/reference_constructs_from_temporary.hpp" // IWYU pragma: export
#include "type_traits/reference_converts_from_temporary.hpp"   // IWYU pragma: export
#include "type_traits/remove_all_extents.hpp"                  // IWYU pragma: export
#include "type_traits/remove_const.hpp"                        // IWYU pragma: export
#include "type_traits/remove_cv.hpp"                           // IWYU pragma: export
#include "type_traits/remove_cvref.hpp"                        // IWYU pragma: export
#include "type_traits/remove_extent.hpp"                       // IWYU pragma: export
#include "type_traits/remove_pointer.hpp"                      // IWYU pragma: export
#include "type_traits/remove_reference.hpp"                    // IWYU pragma: export
#include "type_traits/remove_volatile.hpp"                     // IWYU pragma: export
#include "type_traits/underlying_type.hpp"                     // IWYU pragma: export
#include "type_traits/unwrap_ref_decay.hpp"                    // IWYU pragma: export
#include "type_traits/unwrap_reference.hpp"                    // IWYU pragma: export

#endif
