// yutool: include guard
#ifndef YU_META_FUNCTIONS_CONCEPTS_DETAIL_UNDEF_MACROS_HPP_
#define YU_META_FUNCTIONS_CONCEPTS_DETAIL_UNDEF_MACROS_HPP_

#ifdef DEFINE_FUNCTION_OBJECT
#undef DEFINE_FUNCTION_OBJECT
#endif

#ifdef DEFINE_UNARY_CONCEPT
#undef DEFINE_UNARY_CONCEPT
#endif

#ifdef DEFINE_BINARY_CONCEPT
#undef DEFINE_BINARY_CONCEPT
#endif

#ifdef DEFINE_TERNARY_CONCEPT
#undef DEFINE_TERNARY_CONCEPT
#endif

#ifdef DEFINE_AT_LEAST_ONE_ARITY_CONCEPT
#undef DEFINE_AT_LEAST_ONE_ARITY_CONCEPT
#endif

#ifdef DEFINE_AT_LEAST_TWO_ARITY_CONCEPT
#undef DEFINE_AT_LEAST_TWO_ARITY_CONCEPT
#endif

#ifdef DEFINE_VARIADIC_CONCEPT
#undef DEFINE_VARIADIC_META_FUNCTION
#endif

//

#endif
