#ifdef DEFINE_FUNCTION_OBJECT
#undef DEFINE_FUNCTION_OBJECT
#endif

#ifdef DEFINE_UNARY_TRAIT
#undef DEFINE_UNARY_TRAIT
#endif

#ifdef DEFINE_BINARY_TRAIT
#undef DEFINE_BINARY_TRAIT
#endif

#ifdef DEFINE_TERNARY_TRAIT
#undef DEFINE_TERNARY_TRAIT
#endif

#ifdef DEFINE_AT_LEAST_ONE_ARITY_TRAIT
#undef DEFINE_AT_LEAST_ONE_ARITY_TRAIT
#endif

#ifdef DEFINE_AT_LEAST_TWO_ARITY_TRAIT
#undef DEFINE_AT_LEAST_TWO_ARITY_TRAIT
#endif

#ifdef DEFINE_VARIADIC_TRAIT
#undef DEFINE_VARIADIC_META_FUNCTION
#endif